### PR TITLE
(feat) change to a pyproject.toml to publish to pypi

### PR DESCRIPTION
**Pull request by timcera**
* Moved metadata from setup.py to pyproject.toml and removed setup.py
* Moved README.md to README.rst and rewrote.
* Made a VERSION file to contain version number.
  + Allows version number to be read by pyproject.toml.
  + Refactored _version.py to read version number from VERSION file.
* Made a publish.py to ease and document publishing to pypi.

### CODE REVIEW

**Comment by PaulDudaRESPEC** [comment]
Thanks @timcera !

**Comment by aufdenkampe** [comment]
@timcera, thanks for these updates! Moving to use of a `pygroject.toml` will really facilitate adoption through much better packaging!

I noticed that you replaced `READMD.md` with `README.rst`, which has me thinking that you're getting us setup for automated code documentation with Sphinx, which is awesome. For a lot of our projects, we've been using [Sphinx's Markdown support](https://www.sphinx-doc.org/en/master/usage/markdown.html), because of the higher level of familiarity with Markdown and GithHub's excellent Markdown editors. Just an idea to consider.

**Comment by timcera** [comment]
I tried to stick with markdown, but there was something that wasn't passing the check that would correctly render on PyPI.  The command 'twine check dist/hsp2*tar.gz' validates the README.rst (or README.md).  There was an error with README.md that pointed to a line that didn't have an error that I could see.  So went with what I know works, and once I was finished with the new README.rst it did pass the 'twine check ...'.

**Comment by timcera** [comment]
Noticed that the latest README.rst doesn't render the indented blocks the way I intended.  Will fix soon.

**Pull request merged**
